# file: tasks/common.yml

---
- name: common | aptitude install python-software-properties
  apt: pkg=python-software-properties state=present

- name: common | apt add repositories apt_repositories
  apt_repository: repo={{ item }} state=present
  with_items: gitlab.common.apt_repositories

- name: common | aptitude upgrade
  apt: update_cache=yes upgrade=yes

- name: common | aptitude install apt_packages
  apt: name={{ item }} state=present update_cache=yes
  with_items: gitlab.common.apt_packages

- name: common | create the GitLab directories
  file: name={{ item }} state=directory
  sudo: yes
  sudo_user: git
  with_items: gitlab.common.directories

- name: common | templates
  template: src={{ item.src }} dest={{ item.dest }}
  with_items: gitlab.common.templates

- name: common | template modes
  file: name={{ item.dest }} owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }}
  with_items: gitlab.common.templates

- name: common | symlinks
  file: state=link src={{ item.src }} dest={{ item.dest }} owner={{ item.owner }} group={{ item.group }}
  with_items: gitlab.common.symlinks

- name: common | absent symlinks
  file: name={{ item }} state=absent
  with_items: gitlab.common.absent_symlinks

# source packages --------------------------------------------------------- {{{
- name: common | curl source_packages.tar
  shell: "curl {{ item.src }} | tar xz chdir=/tmp creates={{ item.directory }}"
  with_items: gitlab.common.source_packages.tar

- name: common | git clone source_packages.git
  git: repo={{ item.src }} dest={{ item.directory }}
  with_items: gitlab.common.source_packages.git

- name: common | ./configure source_packages.tar
  command: "{{ item.configure_command }} chdir={{ item.directory }} creates={{ item.configure_creates }}"
  with_items: gitlab.common.source_packages.tar

- name: common | ./configure source_packages.git
  command: "{{ item.configure_command }} chdir={{ item.directory }} creates={{ item.configure_creates }}"
  with_items: gitlab.common.source_packages.git

- name: common | make source_packages.tar
  command: "{{ item.make_command }} chdir={{ item.directory }} creates={{ item.make_creates }}"
  with_items: gitlab.common.source_packages.tar

- name: common | make source_packages.git
  command: "{{ item.make_command }} chdir={{ item.directory }} creates={{ item.make_creates }}"
  with_items: gitlab.common.source_packages.git

- name: common | make install source_packages.tar
  command: "{{ item.make_install_command }} chdir={{ item.directory }} creates={{ item.make_install_creates }}"
  with_items: gitlab.common.source_packages.tar

- name: common | make install source_packages.git
  command: "{{ item.make_install_command }} chdir={{ item.directory }} creates={{ item.make_install_creates }}"
  with_items: gitlab.common.source_packages.git
# /source packages -------------------------------------------------------- }}}
