# file: tasks/repos.yml

---
- name: repos | git clone git_repos
  git: repo={{ item.repo }} dest={{ item.dest }} version={{ item.version }}
  sudo: yes
  sudo_user: git
  with_items: gitlab.repos.git
