# file: tasks/users.yml

---
- name: common | adduser users
  user: name={{ item.name }} password={{ item.password_hash }} shell={{ item.shell }}
  sudo: yes
  sudo_user: root
  with_items: gitlab.users.users
